[package]
name = "burning_ship_fractal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.1"
rand = "0.8.5"
rayon = "1.5.1"
clap = { version = "3.1.8", features = ["derive"] }
